#ifndef _TASKVOICE_H_
#define _TASKVOICE_H_

#include "stm32f10x.h"

#include"..\WTV020\WTV020.h"

#define VOICE_MAX 143
//声音地址枚举
enum{
	VOICE_INSERTCOIN=0,		//投币声0
	VOICE_PLEASECOIN,			//请投币1
	VOICE_PLEASE2COIN,		//请投两个币开始游戏2
	VOICE_PLEASE3COIN,		//请投三个币开始游戏3
	VOICE_PLEASE4COIN,		//请投四个币开始游戏4
	VOICE_PRESSSTARTKEY,	//请按开始键开始游戏吧5
	VOICE_GETBALL,				//请拿球吧6
	VOICE_STARTGAME,				//开始游戏7
	VOICE_GAMESTART,				//游戏开始8
	
	VOICE_TICKETERROR=0x0a,			//彩票器故障
	VOICE_CONNECTSERVER,				//请与服务员联系	
	
	
	VOICE_GETSECONDPRIZE=0x11,	//你很厉害啊// 二等奖
	VOICE_WISHYOU,							//恭喜你//超级大奖用
	VOICE_GETFIRSTPRIZE,				//你获得超级大奖//一等奖
	VOICE_BALLOVER,							//游戏结束//球用完了
	
	VOICE_TIMEOVER=0x17,				//游戏已经超时
	VOICE_GETTHIRDPRIZE,				//你真棒//三等奖
	
	VOICE_TRYTOPLAY=0x1a,				//快来玩玩试试手气吧，背景音乐完后
	VOICE_CONNECTSERVETOGETGIFT,
  VOICE_INBALL=0x1f,					//球进洞声音
	VOICE_MUSIC,								//闲时音乐
  VOICE_THANKUSE=0x73,//感谢您使用
	VOICE_RONGXIANGMACHINE,//荣翔动漫的设备
	VOICE_MACHINESTOPUSE,//设备故障请停止使用
	VOICE_TOTALCOIN=0x76,
	VOICE_TOTALGIFT,//77
	VOICE_TOTALSMALLPRIZE,//78
	VOICE_TOTALBIGPRIZE,//79
	VOICE_TOTALSUPERPRIZE,//7a
	VOICE_EGG,//7b
	VOICE_TOTALEGG,//7c
	VOICE_TICKET,//7d
	VOICE_TOTALTICKET,//7e
	VOICE_GE,//7f
	VOICE_ZHANG,//80
	
	VOICE_0=0x81,
	VOICE_1,
	VOICE_2,
	VOICE_3,
	VOICE_4,
	VOICE_5,
	VOICE_6,
	VOICE_7,
	VOICE_8,
	VOICE_9,
	VOICE_10,
	VOICE_100,
	VOICE_1000,
	VOICE_10000,
	VOICE_STOP=0xfe,						//暂停播放
};
void vVoiceTask( void *pvParameters );

#endif
